package com.example.demo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "Inventory")
public class Inventory {

    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    private String uuid;
    @DynamoDBAttribute
    private String bookUuid;
    @DynamoDBAttribute
    private int quantity;

}
