name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master"]
    types: [closed]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MY_AWS_REGION: ${{ secrets.MY_AWS_REGION }}
      SPRING_PROFILES_ACTIVE: aws
    steps: 
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: action-github-artifacts
    - name: Excute
      run: |
        ls -R
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag binhtt13122000/upload-service:$(date +%s)
