name: Build Artifacts

on: 
  pull_request:
    branches: [master]
env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MY_AWS_REGION: ${{ secrets.MY_AWS_REGION }}
      SPRING_PROFILES_ACTIVE: aws
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir -p artifacts/target && cp target/*.jar artifacts/target && cp Dockerfile artifacts 
        cd artifacts && ls
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: action-github-artifacts
        path: artifacts

  docker:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MY_AWS_REGION: ${{ secrets.MY_AWS_REGION }}
      SPRING_PROFILES_ACTIVE: aws
    steps: 
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: action-github-artifacts
    - name: Excute
      run: |
        ls -R
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag binhtt13122000/upload-service:$(date +%s)


